### ISSUE TITLE
Error: No provider for CustomResource with custom functions (data, callback) 

### ISSUE THREAD

**Issue by growthclick** [troyanskiy/ng2-resource-rest#62]
@troyanskiy Have there been some significant breaking changes in the last couple months? I'm struggling to get my resource classes (with custom functions like below) to work on 1.5.4. Here is an example of a custom function that used to work: 

  @ResourceAction({
        method: RequestMethod.Get,  
        path: '/request/{id}' // Will overwrite default path
  })
  public getById(data:any, callback?:Function): ResourceResult { return null; }

If I add <any> after ResourceResult, it will compile on TSC / JIT for development purposes (e.g. using Ionic serve with Ionic RC3), but when doing a production build, I'm running into errors like "(Error: main.js:62534 Error: No provider for e!)" where e is the resource class I'm trying to inject (as a service in a constructor).  

Based on your examples / documentation, it seems like ResourceMethod might have replaced ResourceResult.  Is that correct and could you please share an example of how to do a custom function that accepts a flexible data parameter and executes a callback as in above? 

Thanks

**Comment by troyanskiy** [comment]
Hello.

Try to use it like that
```ts

@ResourceAction({
  method: RequestMethod.Get,
  path: '/request/{id}' // Will overwrite default path
})
// Old way
// public getById(data:any, callback?:Function): ResourceResult { return null; }

// New way
// <any, any> - first type is INPUT data type, second - OUTPUT data type
getById: ResourceMethod<any, any>;

// Better like that
// getById: ResourceMethod<{id: string /* number or any other type */}, IOutputData>;
```

**Comment by growthclick** [comment]
Thanks @troyanskiy for the super quick reply. Here is the error that comes up (when running with Ionic serve / TSC & JIT) using the new way with getById: ResourceMethod<any, any>;  

![image](https://cloud.githubusercontent.com/assets/5842645/20936793/d76eefba-bb98-11e6-9dee-4e5c465a680f.png)

error_handler.js:53 Error: No provider for RequestAgentService!
    at NoProviderError.BaseError [as constructor] (errors.js:24)
    at NoProviderError.AbstractProviderError [as constructor] (reflective_errors.js:42)

**Comment by troyanskiy** [comment]
I can't check now.
But it's definitely related to ResourceModule.forRoot() in NgModule and JIT compilation.
I will check that ASAP, because I will also need to use it with ionic2.

**Comment by growthclick** [comment]
Okay, thanks for the help and feedback. I'll do some troubleshooting and let you know if I make any progress.

**Comment by growthclick** [comment]
I got it working - the root issue with the no provider message was an error in the NGModule definition. 

With some more updates, I have my original base resource class (GCResource) taking care of authentication, server URL, and standard CRUD operations (similar to what you have in the docs, but with 'id' as an optional parameter).  

In case it helps others, here are the examples working with Ionic 2 RC3 in both development and NGC production build: 


`
import {Resource, ResourceAction, ResourceMethod, ResourceParams} from "ng2-resource-rest";
import {Injectable, Injector} from "@angular/core";
import {RequestMethod, Http} from "@angular/http";
import {AppConfig} from '../../config/app-config';
import {UserService} from '../user/user.service';

@Injectable()
@ResourceParams({add2Provides: false})

export class GCResource extends Resource {
  // extends Resource with authentication headers, standard CRUD requests, and other dynamic server URL (for prod vs dev)

  startPath:any = ''; 

  constructor(http: Http, injector: Injector) {  super(http, injector); }

  @ResourceAction({
    isArray: true
  })
  query: ResourceMethod<any, any>;

  @ResourceAction({
    path: '/{id}'
  })
  get: ResourceMethod<any, any>;

  @ResourceAction({
    method: RequestMethod.Post
  })
  save: ResourceMethod<any, any>;

  @ResourceAction({
    method: RequestMethod.Put,
    path: '/{id}'
  })
  update: ResourceMethod<any, any>;;

  @ResourceAction({
    method: RequestMethod.Delete,
    path: '/{id}'
  })
  remove: ResourceMethod<{id: any}, any>;

  getUrl(): string {
    // AppConfig class is populated with a build script so it can generate the server URL (e.g. prod vs. dev)
    return new AppConfig().url() + this.startPath;
  }
  getHeaders(): any {
    // Prepare headers with user authentication token (JWT) if it exists. lastToken is a static property of User Authentication service 
    var authToken = UserService.lastToken;
    var authHeaders:any = {
            'Accept': 'application/json',
            'Content-Type': 'application/json'
    };
    if (authToken) {
          var bearer = 'Bearer ' + authToken;
          authHeaders['Authorization'] = bearer;
    }
    return authHeaders;
  }
}
`
Each resource class can be quite short as in this example: 

`import {ResourceParams, ResourceAction, ResourceMethod}  from "ng2-resource-rest"; 
import {Injectable, Injector} from "@angular/core";
import {RequestMethod, Http} from "@angular/http";
import {GCResource} from "../../services/gc-resource/gc-resource"; // API Helper library 

@Injectable()

@ResourceParams({
  path: '/request/agent'
})

export class RequestAgentService extends GCResource  {

  // This seems unnecessary but not having it was causing a production NGC build error 
  constructor(http: Http, injector: Injector) {  super(http, injector); }
 
  @ResourceAction({
        method: RequestMethod.Get, // Mandatory field
        path: '/request/{id}' // Will overwrite default path
  })
  // old way public getById(data:any, callback?:Function): ResourceResult<any> { return null; }
  // new way (loosely defined with any input and any output)
  getById: ResourceMethod<any, any>;
}`

There was some troubleshooting with "ionic build" / ngc compilation. I have GCResource being imported as a provider before its child classes.  

After the imports in app.module.ts, here is the rest: 

`@NgModule({
  declarations: [MyApp, PAGES, DIRECTIVES, PIPES],
  imports: [ ResourceModule.forRoot(),
    IonicModule.forRoot(MyApp, {mode: "ios", prodMode: true})],
  bootstrap: [IonicApp],
  entryComponents: [MyApp,PAGES],
  providers: [ AppConfig, HttpModule, GCResource, Storage, CORE_SERVICES, 
	{provide: ErrorHandler, useClass: IonicErrorHandler}]
})
export class AppModule {}`

**Comment by troyanskiy** [comment]
@growthclick thanks a lot for your investigation.
Initially I wanted to test with creating barrel file for all injectable resources and include it into the `app.module` file. I'm not sure, but I think NGC will do files opening/parsing/compilation and since they will be "executed" they will be added to ResourceProviders array, which are used by calling `ResourceModule.forRoot()`

**Comment by growthclick** [comment]
I'm doing the barrel file approach (http://tattoocoder.com/angular2-barrels/) with the injectable resources in the CORE_SERVICES constant in the above code. I'm not sure if it makes a difference but I put GCResource (Base class) ahead of it in the providers list, and also put ResourceModule.forRoot() ahead of the IonicModule.forRoot.  

Despite sequencing efforts, there are a couple resources (that are injected immediately during app startup) where extending GCResource created an error, and so I had to implement them by extending ResourceCRUD.  Working on a deadline so just glad to have a working model now. 

I think you're right about NGC doing the opening/parsing/compilation. I had some "no provider errors" due to missing resource classes in the @NGModule definition, though these issues only came up in the NGC build, not in JIT.
